Repository SOPT-all/36-COLLABORATION-ANDROID-TODO-MATE, pull requests merged in 2025-05, with the labels that each got.

#1 Feature/project setting
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PR_TEMPLATE.md
Labels: 🐹 나경, 🛫 초기세팅

#4 Feature/#3 font resource/ system
  app/src/main/java/com/example/myapplication/ui/theme/Type.kt
  app/src/main/java/com/example/myapplication/ui/theme/Typography.kt
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
Labels: 🐹 나경, 🛫 초기세팅

#6 init/#5 color init setting
  app/src/main/res/values/colors.xml
Labels: 🐱 지영, 🛫 초기세팅

#8 Feature/#7 Make Screens
  app/src/main/java/com/example/myapplication/presentation/custom/HeaderLayout.kt
  app/src/main/java/com/example/myapplication/presentation/home/calender/CalenderScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/category/CategoryScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/etc/EtcScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/importance/ImportanceScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/profile/ProfileBoxScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/profile/ProfileScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/routine/RoutineDatePickerScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/routine/RoutineRepeatScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/routine/RoutineScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/toolBox/ToolBoxScreen.kt
  app/src/main/java/com/example/myapplication/presentation/main/component/MainBottomBar.kt
  app/src/main/java/com/example/myapplication/presentation/util/dialog/AlertDialog.kt
  app/src/main/java/com/example/myapplication/presentation/util/dialog/BoxDialog.kt
Labels: 🐨 종우, 🛫 초기세팅

#10 init/#9 theme init setting
  app/src/main/java/com/example/myapplication/presentation/main/MainActivity.kt
  app/src/main/java/com/example/myapplication/ui/theme/Color.kt
  app/src/main/java/com/example/myapplication/ui/theme/Theme.kt
  app/src/main/java/com/example/myapplication/ui/theme/Typography.kt
Labels: 🐱 지영, 🛫 초기세팅

#15 Feature/#14 ToolBar Layout
  app/src/main/java/com/example/myapplication/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/toolBox/ToolBarScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/toolBox/ToolBoxScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/toolBox/component/ToolBarButton.kt
  app/src/main/res/drawable/icon_importance.xml
  app/src/main/res/values/strings.xml
Labels: 🧩 기능, 🐨 종우

#17 Feature/#13 top view
  app/build.gradle.kts
  app/src/main/java/com/example/myapplication/presentation/custom/HeaderComponent.kt
  app/src/main/java/com/example/myapplication/presentation/home/calender/CalendarTitleComponent.kt
  app/src/main/java/com/example/myapplication/presentation/home/calender/CalendarViewModel.kt
  app/src/main/java/com/example/myapplication/presentation/home/calender/CalenderScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/calender/DayItemComponent.kt
  app/src/main/java/com/example/myapplication/presentation/home/calender/Weekday.kt
  app/src/main/java/com/example/myapplication/presentation/home/profile/PeopleBoxItemComponent.kt
  app/src/main/java/com/example/myapplication/presentation/home/profile/ProfileBoxComponent.kt
  app/src/main/res/drawable/ic_moveleft.xml
  app/src/main/res/drawable/ic_moveright.xml
  app/src/main/res/values/strings.xml
Labels: 🧩 기능, 🐱 지영

#18 Feature/#11 루틴등록/ 우선순위 뷰 구현
  app/build.gradle.kts
  app/src/main/java/com/example/myapplication/presentation/component/ImportanceSelector.kt
  app/src/main/java/com/example/myapplication/presentation/component/RepeatCycleSelector.kt
  app/src/main/java/com/example/myapplication/presentation/component/TodomatePicker.kt
  app/src/main/java/com/example/myapplication/presentation/home/importance/ImportanceScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/routine/RoutineDatePickerScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/routine/RoutineEndScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/routine/RoutineRepeatScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/routine/RoutineScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/routine/RoutineStartScreen.kt
  app/src/main/java/com/example/myapplication/ui/theme/Typography.kt
  app/src/main/res/drawable/ic_importance_lower.xml
  app/src/main/res/drawable/ic_importance_middle.xml
  app/src/main/res/drawable/ic_importance_upper.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🧩 기능, 🐹 나경

#23 Feature/#13 top view 보충
  app/src/main/java/com/example/myapplication/presentation/home/calender/CalenderScreen.kt
  app/src/main/java/com/example/myapplication/presentation/home/calender/component/CalendarTitleComponent.kt
  app/src/main/java/com/example/myapplication/presentation/home/calender/component/DayItemComponent.kt
Labels: 🐱 지영
